require 'plugins.guess-indent'
require 'plugins.gitsigns'
require 'plugins.which-key'
require 'plugins.colorscheme'
require 'plugins.todo-comments'
require 'plugins.mini'
require 'plugins.telescope'
require 'plugins.fidget'
require 'plugins.lsps'
require 'plugins.conform'
require 'plugins.snippets'
require 'plugins.blink'
require 'plugins.treesitter'

-- vim: ts=2 sts=2 sw=2 et
